name: Deploy Website

on:
  workflow_dispatch: {}

jobs:
  test:
    uses: dicebear/dicebear/.github/workflows/test.yml@8.x
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Download legal pages
        env:
          PAT: ${{ secrets.PAT }}
        run: ./apps/docs/scripts/download-legal-pages.sh

      - name: Build with VitePress
        run: npm run build -- --ignore "@dicebear/@(cli|editor)"

      - name: Deploy to Bunny.net
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.2
        with:
          source: 'apps/docs/.vitepress/dist'
          destination: ''
          storageZoneName: '${{ secrets.WEBSITE_STORAGE_NAME }}'
          storagePassword: '${{ secrets.WEBSITE_STORAGE_PASSWORD }}'
          accessKey: '${{ secrets.CDN_ACCESS_KEY }}'
          pullZoneId: '${{ secrets.WEBSITE_PULL_ZONE_ID }}'
          upload: 'true'
          remove: 'true'
          purgePullZone: 'true'
